### ISSUE TITLE
Do we need 2 organizations?

### ISSUE THREAD

**Issue by GrahamSH-LLK** [snapblock/mediawikisnapblock#2]
@R4356th We already have the snapwiki organization, shouldn't we move this to snapwiki, instead of having 2 organizations?

**Comment by RubenVerg** [comment]
+1

**Comment by space-elephant** [comment]
No, because we should also use it on https://forum.snap.berkeley.edu.

**Comment by RubenVerg** [comment]
I don’t think that’s supportable. It’s a mediawiki extension, plus (I guess) it’s like sayng “oh I made a library for my project, oh hey let’s make it public”, no need to move it anywhere. Plus, an organization in GH should be *an organization*, not a way of classifying projects.

**Comment by RubenVerg** [comment]
I don’t think that’s supportable. It’s a mediawiki extension, plus (I guess) it’s like sayng “oh I made a library for my project, oh hey let’s make it public”, no need to move it anywhere. Plus, an organization in GH should be *an organization*, not a way of classifying projects.

**Comment by space-elephant** [comment]
scratchblocks is the same library for mediawiki and for anything else. The mediawiki wrapper is fairly small. However, the team is about the same, so you can move it easily.

**Comment by RubenVerg** [comment]
everything else remains: no need for 2 orgs of the same people

**Comment by GrahamSH-LLK** [comment]
Agreed. I think we need @R4356th to move it. What do you think, R4356th?

**Comment by R4356th** [comment]
> 
> 
> Agreed. I think we need @R4356th to move it. What do you think, R4356th?

This organization has some other deals, too. As @space-elephant has said, I am also trying to make an extension for Discourse and thus for the forums.

**Comment by RubenVerg** [comment]
that doesn't mean we are two separate entities, tho
